### ISSUE TITLE
Not working with 1.13.2?

### ISSUE THREAD

**Issue by fiveseven808** [Reiya1013/VMCAvatarMaterialChange#1]
So I'm not sure if I'm doing anything wrong as this is the first time I'm using this mod. I can see the mod settings and change them around, but my avatar is still white. I have 1.13.2. I assumed it was a minor release so it should be fine. Does anyone else have this issue?

**Comment by Reiya1013** [comment]
Hi, fiveseven808

The operation has been confirmed in 1.13.2.
If it now turns white, the shader may be UniUnlit.
The only shaders supported by Material Change are Standard and Mtoon.
Would you please check if it is one of these two?

**Comment by fiveseven808** [comment]
Hi Reiya1013, you are correct. I had UniUnlit shaders in use. After switching to Mtoon, it started to work properly. 

Thank you so much for this plugin!
